### ISSUE TITLE
Sono Hanabira ni Kuchizuke o ?

### ISSUE THREAD

**Issue by imKota** [regomne/chinesize#10]
Hello!
Can you add game support?

Sono Hanabira ni Kuchizuke o *

**Comment by 0xh3LL0** [comment]
since you didnt ask for specific i assume you ask for script support
there is a tool called [ArcTool](https://tlwiki.org/?title=Tools#)  for that
according to the author it support Sono hanabira 1-8, Sono Hanabira Watashi no Ouji-sama, and Sono Hanabira Anata wo Suki na Shiawase, but maybe it can be used for newer Sono Hanabira as well...
![arctool_hanabira](https://user-images.githubusercontent.com/23132217/41134923-22389580-6af9-11e8-9176-2dd240a9261e.png)
![hanabira](https://user-images.githubusercontent.com/23132217/41134928-31b49478-6af9-11e8-8a1f-f0a591ef7d98.png)

**Comment by imKota** [comment]
@0xh3LL0 
Thanks for your reply!
From the first to the eighth chapsties, I used ArcTool.
The other day I solved the problem with the new parts. those that followed the 9 parts go.

**Comment by Reivin1** [comment]
alguien tiene la herramienta actualizada y como se  utiliza

**Comment by Reivin1** [comment]
someone has the updated tool and how to use it
