### ISSUE TITLE
QLIE engine

### ISSUE THREAD

**Issue by marcussacana** [regomne/chinesize#4]
I hope I'm not filling the bag, the last time you helped me a lot here by github issues and I came here to ask if you know any tool to repackage .pack files QLIE I to desperate and do not know who to ask, then I saw that you have the folder Qlie and decided to ask TT-TT sorry for the inconvenience

--sorry my english (i use google translate)
--i'am brazilian
(to koiken otome)

**Comment by regomne** [comment]
.pack of QLIE has 3 versions. You need to know which version do you want. You can visit http://asmodean.reverse.net/pages/exfp3.html and loot at his src code.
I'm busy recently because Chinese New Year is coming, so I'm afraid not having time to tell you how to use his code.
P.S. if you can say Japanese, say that instead of English.

**Comment by rr-** [comment]
In case of Koiken Otome, you need to supply fkey and path to game exe.

If you wish to create a packer yourself:

1. Version 1.47+ includes guessing the key from game exe, which is required for this game.
2. The website, however, provides source code only for 1.46.
3. To find the `.exe` key manually:
    1. Locate the last occurence of `\x05TIcon` within the game's executable.
    2. The key is located right after that.
    3. The key is 256 bytes long.

If I were you, instead of asking for different packers every week, I'd focus on one game and finish the job.
